# -*- coding: utf-8 -*-
"""ThreatGuardAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yVNNqxZyq4RHtIGxByYrhcA1Z2hTOVKB
"""

import pandas as pd
import requests
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import joblib
url = "https://raw.githubusercontent.com/defcom17/NSL_KDD/master/KDDTrain%2B.txt"
res = requests.get(url)
with open("KDDTrain+.txt", "wb") as f:
    f.write(res.content)
columns = [
    'duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
    'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted',
    'num_root', 'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds',
    'is_host_login', 'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate',
    'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate',
    'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
    'dst_host_srv_serror_rate', 'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'attack', 'level'
]

df = pd.read_csv("KDDTrain+.txt", names=columns, header=None)
print("Dataset Shape:", df.shape)
df.head()



categorical_columns = ['protocol_type', 'service', 'flag']

le = LabelEncoder()
for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

df['attack'] = df['attack'].apply(lambda x: 0 if x == 'normal' else 1)

print("Class Distribution:")
print(df['attack'].value_counts())

import matplotlib.pyplot as plt
counts = df['attack'].value_counts()
counts.plot(kind='bar', color=['blue', 'red'])
plt.title('Distribution of Normal (0) vs Attack (1)')
plt.xticks([0, 1], ['Normal', 'Attack'], rotation=0)
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop(['attack', 'level'], axis=1)
y = df['attack']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Train set size:", X_train.shape)
print("Test set size:", X_test.shape)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42,
    class_weight='balanced'
)

model.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Generate predictions
y_pred = model.predict(X_test)

# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Model Evaluation Results")
print("-" * 40)
print(f"Accuracy Score: {accuracy * 100:.2f}%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

import seaborn as sns
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(7,6))
sns.heatmap( cm,annot=True, fmt='d',cmap='RdYlGn', linewidths=0.5, linecolor='black', xticklabels=['Normal', 'Attack'], yticklabels=['Normal', 'Attack'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (Random Forest)')
plt.show()

importances = model.feature_importances_
indices = np.argsort(importances)[-10:]
plt.figure(figsize=(10,6))
plt.title('Top 10 Important Features')
plt.barh(range(len(indices)), importances[indices], align='center')
plt.yticks(range(len(indices)), [X.columns[i] for i in indices])
plt.xlabel('Relative Importance')
plt.show()

import joblib
from google.colab import files

joblib.dump(model, 'ids_random_forest_model.joblib')
joblib.dump(scaler, 'data_scaler.joblib')

files.download('ids_random_forest_model.joblib')
files.download('data_scaler.joblib')

!pip install skl2onnx onnx onnxruntime

from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType
import onnx
from google.colab import files

n_features = X_train.shape[1]

initial_type = [
    ('float_input', FloatTensorType([None, n_features]))
]

model_onnx = convert_sklearn(model, initial_types=initial_type)

with open("ids_random_forest.onnx", "wb") as f:
    f.write(model_onnx.SerializeToString())

onnx.checker.check_model(model_onnx)

scaler_onnx = convert_sklearn(scaler, initial_types=initial_type)

with open("scaler.onnx", "wb") as f:
    f.write(scaler_onnx.SerializeToString())

onnx.checker.check_model(scaler_onnx)

files.download("ids_random_forest.onnx")
files.download("scaler.onnx")